#!/bin/bash

# This script converts a DSSP ss.xpm file 
# (generated by the do_dssp Gromacs tool) 
# to a Gnuplot script, and executes this 
# Gnuplot script, in order to plot the
# time evolution of the secondary struc-
# ture content.
# The output is a .png file with the
# time evolution of the secondary struc-
# ture content.

# To run it, execute: 
# ./plot_sscontent_vs_time.sh outputPlotFile.png 0.05

outplot=$1 # Output plot file 
ts=$2 # Time step in ns (for our simulations,
# this is 0.05)
fr=421 # Index of the first SK2 residue
fp=/scratch/rafael/CaMRecog # Full path 

for sys in SK227-43 SK2Prehelix
do

# Input ss.xpm file
indata=${fp}/${sys}/ProdLonger/R0/ss.xpm 

outdata=${fp}/${sys}/ProdLonger/R0/ss.dat

# First line (fl) of DSSP matrix 
fl=$(grep -n y-axis ${indata} | tail -1 | cut -f 1 -d :)
fl=$((fl+1))
sed -n ${fl},'$'p ${indata} | cut -f 2 -d '"' > ${outdata} 

# Reverse the line order
awk 'BEGIN{i=0}{ \
  line[i]=$0; i++} \
  END{for (i=NR-1;i>=0;i--) print line[i] \
  }' ${outdata} > tmp; mv tmp ${outdata}

# Replace DSSP symbols with numbers
sed -i -e "s/\~/ 0 /g" -e "s/E/ 1 /g" -e "s/B/ 2 /g" \
-e "s/S/ 3 /g"  -e "s/T/ 4 /g" -e "s/H/ 5 /g" \
-e "s/I/ 6 /g" -e "s/G/ 7 /g" ${outdata} 

done

# Write gnuplot script 
cat << EOF > plot_dssp.gpl 
set terminal pngcairo enhanced size 33.33cm,41.67cm font ",18 
set output "${outplot}" 
set autoscale fix
set cbrange [-0.5:7.5]
set palette defined (0 "#FFFFFF", 1 "#FFFFFF", 1 "#FF0000", \
2 "#FF0000", 2 "#000000", 3 "#000000", 3 "#008000", 4 "#008000", \
4 "#FFFF00", 5 "#FFFF00", 5 "#0000FF", 6 "#0000FF", 6 "#800080", \
7 "#800080", 7 "#808080", 8 "#808080")
set cbtics scale 0 ("Coil" 0,"{/Symbol b}-Sheet" 1,"{/Symbol b}-Bridge" 2,\
"Bend" 3,"Turn" 4,"{/Symbol a}-Helix" 5,"5-Helix" 6,"3-Helix" 7) out \
offset 0,0.5 font ",15" 
set colorbox user size 0.85,0.007 origin 0.11,0.03 horizontal 
unset xlabel 
set ylabel "Residue"
set ytics 424,4,436 
set multiplot layout 3,1 font ",18" 
set tmargin at screen 0.90; set bmargin at screen 0.75 
set title "SK2 (N421-T437, one turn, in solution)" 
set label 1 "A" at graph 0,1.2 front font ",35" 
# This is the system in aqueous solution, from our previous work
plot "~/CaMRecog/1KKD/Prod/R0/ss.dat" \
matrix u (\$1*${ts}):(\$2+${fr}):3 with image notitle 
set tmargin at screen 0.60; set bmargin at screen 0.45 
set title "SK2 (N421-T437, one turn, bonded to CaM)"
set label 1 "B" 
plot "${fp}/SK227-43/ProdLonger/R0/ss.dat" \
matrix u (\$1*${ts}):(\$2+${fr}):3 with image notitle 
set tmargin at screen 0.30; set bmargin at screen 0.15 
set title "SK2 (N421-T437, two turns, bonded to CaM)"
set label 1 "C" 
set xlabel "Time (ns)"
plot "${fp}/SK2Prehelix/ProdLonger/R0/ss.dat" \
matrix u (\$1*${ts}):(\$2+${fr}):3 with image notitle 
unset multiplot
EOF

# Run gnuplot script and delete it
gnuplot plot_dssp.gpl
rm plot_dssp.gpl
