#!/bin/bash

# This script converts a DSSP ss.xpm file 
# (generated by the do_dssp Gromacs tool 
# through the pbc-SS_iqmotifs.sh script)_
# to a Gnuplot script, and executes this 
# Gnuplot script, in order to plot the
# time evolution of the secondary struc-
# ture content.
# The output is a .png file with the
# time evolution of the secondary struc-
# ture content.

# To run it, execute: 
# ./plot_sscontent_vs_time_additionalIQmotifs.sh 
# outputPlotFile.png 0.05

outplot=$1 # Output plot file 
ts=$2 # Time step in ns (in our case, 0.05) 

# Change this path as needed
sfp=/scratch/rafael/CaMRecog/AdditionalIQmotifs 
# Semi-full path

for motif in sk1 sk4 kcnq1 kcnq2 
# (First four; for the last four, change the names, 
# both heere and in the Gnuplot script written below)
do

# Change these paths as needed
sfp=/scratch/rafael/CaMRecog/AdditionalIQmotifs 
fp=${sfp}/${motif} # Full path 
indata=${fp}/ss.xpm
outdata=${fp}/ss.dat

# First line (fl) of DSSP matrix 
fl=$(grep -n y-axis ${indata} | tail -1 | cut -f 1 -d :)
fl=$((fl+1))
sed -n ${fl},'$'p ${indata} | cut -f 2 -d '"' > ${outdata} 

# Reverse the line order
awk 'BEGIN{i=0}{ \
  line[i]=$0; i++} \
  END{for (i=NR-1;i>=0;i--) print line[i] \
  }' ${outdata} > tmp; mv tmp ${outdata}

# Replace DSSP symbols with numbers
sed -i -e "s/\~/ 0 /g" -e "s/E/ 1 /g" -e "s/B/ 2 /g" \
-e "s/S/ 3 /g"  -e "s/T/ 4 /g" -e "s/H/ 5 /g" \
-e "s/I/ 6 /g" -e "s/G/ 7 /g" ${outdata} 

done

# Write gnuplot input
cat << EOF > plot_dssp.gpl 
set terminal pngcairo enhanced size 50cm,50cm 
set output "${outplot}" 
set autoscale fix
set cbrange [-0.5:7.5]
set palette defined (0 "#FFFFFF", 1 "#FFFFFF", 1 "#FF0000", \
2 "#FF0000", 2 "#000000", 3 "#000000", 3 "#008000", 4 "#008000", \
4 "#FFFF00", 5 "#FFFF00", 5 "#0000FF", 6 "#0000FF", 6 "#800080", \
7 "#800080", 7 "#808080", 8 "#808080")
set cbtics scale 0 ("Coil" 0,"{/Symbol b}-Sheet" 1,"{/Symbol b}-Bridge" 2,\
"Bend" 3,"Turn" 4,"{/Symbol a}-Helix" 5,"5-Helix" 6,"3-Helix" 7) out font ",15" 
set colorbox user size 0.75,0.0125 origin 0.15,0.05 horizontal 
set xlabel "Time (ns)" font ",18"
#set xtics 0,20 font ",18" 
set ylabel "Residue" font ",18"
set multiplot layout 2,2 
set tmargin at screen 0.90; set bmargin at screen 0.60
set title "KCNN1" font ",18"
plot "${sfp}/sk1/ss.dat" \
matrix u (\$1*${ts}):(\$2+393):3 with image notitle 
set title "KCNN4"
plot "${sfp}/sk4/ss.dat" \
matrix u (\$1*${ts}):(\$2+313):3 with image notitle 
set tmargin at screen 0.46; set bmargin at screen 0.16 
set title "KCNQ1"
plot "${sfp}/kcnq1/ss.dat" \
matrix u (\$1*${ts}):(\$2+369):3 with image notitle 
set title "KCNQ2"
plot "${sfp}/kcnq2/ss.dat" \
matrix u (\$1*${ts}):(\$2+334):3 with image notitle 
unset multiplot
EOF

gnuplot plot_dssp.gpl
rm plot_dssp.gpl
