#!/bin/bash

# Script to compute the average and standard deviation (in kcal/mol)
# of the last five free energy surfaces as a function of the collective 
# variable (CaM-W431 Calpha-W431 aromatic ring).

# To run it, execute ./compute_av_std_last_five_fes.sh 
# (in the directory with the fes_*dat files generated by the
# genFESMetad.sh script).

# The generated fes_av_std_5.dat file contains the average 
# and standard deviation of the last five FES surfaces.

c=0
for fes in 45 46 47 48 49 # the last five FES surfaces; change the numbers as needed
do
    if [ ${c} == 0 ]
    then 
        awk '{if (substr($1,1,1)!="#") print $1}' fes_${fes}.dat > tmp_cv_values
    fi
    awk '{if (substr($1,1,1)!="#") print $2}' fes_${fes}.dat > tmp${fes} 
    c=$((c+1))
    fes_files=(${fes_files[@]} tmp${fes})
done

paste tmp_cv_values ${fes_files[@]} > fes_last_5.dat 

awk '{sum=0; for(i=2;i<=NF;i++){sum+=$i}; av=sum/(NF-1); \
std=0; for(i=2;i<=NF;i++){std+=($i-av)^2}; std=sqrt(std/(NF-2)); \
{print $1, av/4.184, std/4.184}}' fes_last_5.dat  > fes_av_std_5.dat 
